language: node_js

sudo: required

node_js:
  - "8.12"

services:
  - docker

script:
  - "npm run build"
   - "docker build -t testinguser99/message-app ."

after_success:
  - bash <(curl -s https://codecov.io/bash)