language: node_js

sudo: required

env:
  global:
    - REGISTRY_USER=sivretda

node_js:
  - "8.12"

services:
  - docker

script:
  - "npm run build"
  - "docker build -t sivretda/testing ."

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push sivretda/testing
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)